import '@/styles/globals.css';
import Header from '@/components/Header/header';
import { Rubik } from 'next/font/google';
import { Oswald } from 'next/font/google';
import Head from 'next/head';
import { AuthProvider } from '@/hooks/useAuth';
import { AlertProvider } from '@/hooks/useAlert';
import { ScoresProvider } from '@/contexts/ScoreProvider';
import { QuestionProvider } from '@/contexts/QuestionProvider';

// const workSans = Work_Sans({subsets: ['latin']})
const rubik = Rubik({subsets: ['latin']})
const oswald = Oswald({subsets: ['latin']})


export default function App({ Component, pageProps }) {
  return (
    <>
      <AlertProvider>
        <AuthProvider>
          <ScoresProvider>
            <QuestionProvider>
              <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className={`${rubik.className} ${oswald.className}`}>
                <Header />
                <Component {...pageProps} />
              </main>
            </QuestionProvider>
          </ScoresProvider>
        </AuthProvider>
      </AlertProvider> 
    </>
  ) 
}
