import '@/styles/globals.css'
import { Work_Sans } from 'next/font/google';
import Head from 'next/head'
import { AuthProvider } from '@/hooks/useAuth';
import { AlertProvider } from '@/hooks/useAlert';
import { ScoresProvider } from '@/contexts/ScoreProvider';

const workSans = Work_Sans({subsets: ['latin']})


export default function App({ Component, pageProps }) {
  return (
    <>
      <AlertProvider>
        <AuthProvider>
          <ScoresProvider>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={workSans.className}>
              <Component {...pageProps} />
            </main>
          </ScoresProvider>
        </AuthProvider>
      </AlertProvider> 
    </>
  ) 
}
