import '@/styles/globals.css'
import { Work_Sans } from 'next/font/google';
import Head from 'next/head'
const workSans = Work_Sans({subsets: ['latin']})


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={workSans.className}>
      <Component {...pageProps} />
        </main>
    </>
  ) 
}
